### ISSUE TITLE
Update 404 page

### ISSUE THREAD

**Issue by mfenner** [ror-community/ror-site#1]
Consider using https://www.freeimages.com/photo/lion-1258294

**Comment by ynnig** [comment]
I purchased this if useful. It's sorta "tried but failed, am I'm disappointed in myself"... ?https://files.slack.com/files-pri/TF07SEVPF-FFKH3V5UL/download/stocksy_txp566dad6eecd200_h264_720p_1910973.mov

**Comment by cazinc** [comment]
@ynnig I realise it's probably not a priority, but if you can repost the MOV file you mentioned in your comment of 5 Feb 2019 (or perhaps it's just in a channel I can't access) we'll get it added into the 404 page, which we are planning go fix as part of the Refresh.

**Comment by mariagould** [comment]
@cazinc thanks for picking this up. If the MOV file is no longer available (I don't have it) we could use this image with the text "Sorry, we can't seem to find what you are looking for."

https://unsplash.com/photos/g1zVGpS2j20

**Comment by ynnig** [comment]
Nice image too! Here's the .mov:

https://user-images.githubusercontent.com/6958740/180498043-092ad3b9-60c9-47b6-a6ee-2647e9fee84b.mov

**Comment by cazinc** [comment]
Resolved in the Summer-2022-updates branch. If viewing local, due to the way Hugo works you'll need to go straight to the page to see it: http://localhost:1313/404.html. 

The MOV file was perhaps a bit too big for this, would have resulted in a 14MB download on every 404.
