### ISSUE TITLE
Re-implement banner images

### ISSUE THREAD

**Issue by cazinc** [ror-community/ror-site#19]
Banner images were lost in the new theme.

**Comment by cazinc** [comment]
@ynnig we've now re-implemented banner images on all pages for the ROR site. Tested and committed to dev branch.

Some notes:

1. Most pages are using the orange banner image, so updates may be needed. As before this can be controlled through the `banner` front matter element e.g. `banner = "/img/banners/ROR_Banner-orange.jpg"`
2. We've retained the drop shadow that sits under nav and now at the top of the banner area for consistency, as it appears elsewhere in the new theme. 
3. Individual blog posts now have banner images as well. They are slightly taller - size is dependent on the text within. More than one is using `PrideofLions.jpg` so updates may be needed. Also this particular image is too narrow to work as a banner (refer to `lions-ban.jpg` which is 2000px wide and so works much better). 
4. If no banner image is specified the site will display the new dark orange background colour, #da3200 (this can be changed).

**Comment by ynnig** [comment]
Thanks, @cazinc - I've cleaned up the banners. Need to add a different default - I'm thinking the city banner one we haven't used much but that's on the first blog post. But will close this for now and add that to a styling snagging list for when you're back.
