### ISSUE TITLE
Hamburger nav needs to show sooner

### ISSUE THREAD

**Issue by cazinc** [ror-community/ror-site#20]
At the moment the hamburger nav doesn't show until width is 992px or lower. But between 992px and 1072px this means that the current nav items wrap and look somewhat "broken". See attached screenshot. To start just the twitter icon wraps, but then eventually so does Blog. 

Suggest a quick fix at least of making the hamburger nav appear from 1072 or lower - although note that if nav becomes longer again, this could break it again. 

<img width="996" alt="Screenshot 2019-07-23 at 23 05 57" src="https://user-images.githubusercontent.com/3863704/61750894-86d42980-ad9e-11e9-9a45-e61b3b93753c.png">

**Comment by cazinc** [comment]
Looks like this hasn't been resolved @mariagould - do you want us to try and fix?

**Comment by mariagould** [comment]
Sure, thanks!

**Comment by mariagould** [comment]
I believe this has now been addressed via #30 - closing out.
