### ISSUE TITLE
column shortcode creation

### ISSUE THREAD

**Issue by ynnig** [ror-community/ror-site#22]
Hi @cazinc - can we appropriate the custom column shortcode from m2020 and crossref sites? We probably need `{{% row %}}` as well as `{{% column %}}`.

Thankyee.

**Comment by cazinc** [comment]
Hi @ynnig - sure, we'll get these moved over to ROR (as I think we did back in the day for md2020?).

**Comment by cazinc** [comment]
Hi @ynnig that's ready for you to review, see https://dev.ror.org/test/ on the dev site. If all looks well let me know and I'll delete this test page and you can just merge in the remaining shortcake and css code. 

We've implemented 2, 3 and 4 column layouts but the content area is a bit narrower on ROR, so 4 column in particular are a bit squeezed.
