### ISSUE TITLE
Fix license to be CC0 rather than the current public domain mark

### ISSUE THREAD

**Issue by dhimmel** [ror-community/ror-site#24]
Currently, https://ror.org/ states the following about the licensing or ROR data:

> All ROR IDs and metadata are provided under the [Creative Commons Public Domain 1.0 International](https://creativecommons.org/publicdomain/mark/1.0/) Licence.

I am not sure whether the intention was to apply a [CC0 License / Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) or the [Public Domain Mark](https://creativecommons.org/publicdomain/mark/1.0/)? Currently, the link points to the public domain mark, but the text includes the word "license".

The public domain mark is not a license. The distinction between the PDM and CC0 is [described here](https://wiki.creativecommons.org/wiki/PDM_FAQ#What_is_the_difference_between_the_PDM_and_CC0.3F):

> PDM and CC0 differ in important respects and have distinct purposes. CC0 is intended for use only by authors or holders of copyright and related or neighboring rights (including sui generis database rights), in connection with **works that are still subject to those rights** in one or more jurisdictions. PDM, on the other hand, can be used by anyone, and is intended for use with **works that are already free of known copyright restrictions throughout the world**.
> 
> The tools also differ in terms of their effect when applied to a work. CC0 is legally operative in the sense that when it is applied, it changes the copyright status of the work, effectively relinquishing all copyright and related or neighboring rights worldwide. PDM is not legally operative in any respect -- it is intended to function as a label, marking a work that is already free of known copyright restrictions worldwide.

For the ROR data, I think CC0 is much more appropriate than PDM, because CC0 actually waives any copyright that may exist, ensuring users don't have to worry about the legality of reuse. The PDM is just asserting copyright doesn't cover the ROR data, but that is a complicated question that is jurisdiction dependent. The only way for users to be certain copyright doesn't encumber the data is for the creators to apply a CC0 license.

The following source code is affected:

https://github.com/ror-community/ror-site/blob/25d35545632f6454f714d947ac86771873db7733/themes/hugo-ror/layouts/partials/footer.html#L6

Also present at [ror-community/ror-app](https://github.com/ror-community/ror-app/blob/74ae69899eaae47248db7d67bb9724e28d676d63/app/templates/components/application-footer.hbs#L6-L7).

**Comment by mariagould** [comment]
Thanks for flagging this. We did intend to assert CC0. The information has now been adjusted in the footer.

**Comment by dhimmel** [comment]
Cool! Thanks for looking into this. I see the change in https://github.com/ror-community/ror-site/commit/342d604df393a925cf18bbec5f78c4659e19f4aa.
