### ISSUE TITLE
Search page styling should match rest of ROR site

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#25]
Search page styling should be updated to match the rest of the ROR site. This mainly affects the styling of the navigation links. Will update this ticket with other details. 

Main site navigation links:
![Screen Shot 2020-02-18 at 4 44 07 PM](https://user-images.githubusercontent.com/45110557/74790948-f3989f00-526d-11ea-9d9d-8b7937c98e18.png)

Search page navigation links:
![Screen Shot 2020-02-18 at 4 41 26 PM](https://user-images.githubusercontent.com/45110557/74790949-f4313580-526d-11ea-8658-3e0e778cf0bd.png)

**Comment by cazinc** [comment]
I think this has been addressed already @mariagould - I guess by Martin? I'm comparing to the two nav bars and they seem in line now. Can you confirm or let me know if there are remaining issues?

**Comment by mariagould** [comment]
Looks good! Closing.
