### ISSUE TITLE
Page 2 of ROR blog results in 404

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#26]
If you try to access the second page of the ROR blog (via the "Older" link at the bottom of https://ror.org/blog), it leads to a 404.

https://ror.org//blog/page/2/

I think this is due to the double slash before "blog". If you try https://ror.org/blog/page/2/ it seems to work fine.

@cazinc is this something you are able to look into?

**Comment by cazinc** [comment]
This is now fixed on dev @mariagould, you can test by going to https://dev.ror.org/blog/ and testing the OLDER -> link at bottom (and then the <- NEWER link on the next page). If all good this just needs merged into master branch to make it live.

**Comment by mariagould** [comment]
Thanks @cazinc I tested the link and was able to access the other page successfully. 

A couple of quick questions: Before deploying to master, do we need to merge staging into dev to make sure the latest content is there?

**Comment by cazinc** [comment]
Hi @mariagould - yes, that sounds right.
