### ISSUE TITLE
Make all links in site green, consistently

### ISSUE THREAD

**Issue by cazinc** [ror-community/ror-site#28]
Replace the section-specific colour scheme and make all links the new green colour specified by Maria.

**Comment by cazinc** [comment]
@mariagould I've moved this to a new issue just as it wasn't really related to the initial "make search use the same stylesheet" issue (#11). Can you have a look and close this issue if all looks well now? The darker green colour is used on all links now, in search, blog, etc. 

We tried the darker green in the footer (see attached) but it was just too dark and so would necessitate changing text colour, background colour of the copyright footer (dark grey), etc. What do you think - shall we leave as is for now? 

<img width="1193" alt="Screenshot 2020-03-17 at 21 03 02" src="https://user-images.githubusercontent.com/3863704/76901269-d669e700-6892-11ea-8eaf-7f086087a4d6.png">

**Comment by mariagould** [comment]
@cazinc I'm seeing the new link color only on the Search page and Supporters page. It looks like the other pages still have the red link color. Can you double-check?

For the subscribe footer blog and copyright footer block let's leave those as is for now. I agree it looks too dark in the screenshot you shared.

**Comment by cazinc** [comment]
Hi @Mariagould, I can see it on all other pages - maybe you just need to refresh the pages as you are still seeing cached styles? Screenshot of Facts, Resources and Blog pages attached for ref.




Zach Anthony
Managing Director, Cazinc (Ltd) Digital
Digital consultancy & web development
Tel +44 (0)131 202 6499 | Mob +44 (0)7810 403 497 | Email zach@cazinc.co.uk | Web cazinc.co.uk
Registered in Scotland No. SC287248. VAT Registration No. GB973077006 Cazinc has its registered office at 13/1 Spottiswoode Road, Edinburgh, EH9 1BH. This email and its attachments are confidential and may contain information intended only for the recipient/s named above. Any views or opinions expressed within the email are solely those of its author and do not necessarily represent those of Cazinc Ltd. If you not an intended recipient you are informed that any copying, distribution, disclosure, reliance upon or other use of the contents of this email is strictly prohibited. If you believe you have received this email in error please notify the sender immediately and destroy it.

**Comment by mariagould** [comment]
Sorry for the delay. I've tried all sorts of cache-clearing and I still can't see the changes, unfortunately. But I believe you that they are there! 

Will close this out for now and open a new one if further adjustments are needed. Thanks so much.
