### ISSUE TITLE
Redirect stylesheets to ror.org

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#33]
From Martin: "I suggest to have all stylesheets point to ror.org instead of www.ror.org, as www.ror.org is a redirect to ror.org, requiring an extra step to watch out for."

**Comment by cazinc** [comment]
@mariagould just going through any other pending items. It looks like this issue has already been resolved? Are we safe to close it?

**Comment by mariagould** [comment]
Thanks for flagging @cazinc. This is another low-priority legacy issue in the repo and is being tracked in another project board. Let's keep it open so the team can review along with other infrastructure maintenance.

**Comment by cazinc** [comment]
Of course @mariagould, no prob.
