### ISSUE TITLE
Switch font to Atkinson Hyperlegible

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#45]
The ROR website currently uses the Poppins font. We want to make sure the website is as accessible as possible, and as part of this goal, we plan to change to a more accessible font, Atkinson Hyperlegible (https://brailleinstitute.org/freefont).

**Comment by cazinc** [comment]
Now done in the Summer-2022-updates branch of tor-site. Will create a separate card for roe-app updates.
