### ISSUE TITLE
Update main navigation items

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#48]
We want to make some updates to the main navigation menu on the ROR website. These changes need to be deployed in both ror-site and ror-app. 

Proposed changes are here: https://docs.google.com/document/d/1CCEwnPcbtXpDA9fNTOWIGI73eaqFXZCXV9MI7FAdjlc/edit#

**Comment by cazinc** [comment]
Hi @mariagould just a couple of comments on the new nav structure:

1. It's possible that we are misunderstanding the intent of the Slugs column in the proposed changes doc. but you wouldn't normally want subpages to have a slug off the route. So for example where the new page "History" has a slug of /history, you'd actually want /about/history since it "lives" under About. Assuming you're OK with that we'll just go ahead with this structure. 
2. Related to the above, will there be a need to setup redirects for the old page URLs, e.g. /curation -> /registry/curation or /facts -> /about/faqs? 
2. Having the Resources/Support link in main nav open a new site isn't a good idea. It can be disorientating for users since clicking it takes them away from the site and into a new window, contrary to other items on the main nav. For this sort of thing the usual solution is to set the link apart somehow and indicate that it leads to an external site. I note that a link is already being added to the new links block in the footer (#58), would that be sufficient (plus wherever you might link in content)? If not we could add it as a button/differently styled link near or in main nav, with a clear indication that it's an external link to better set user expectations. 

Let me know if questions.

**Comment by mariagould** [comment]
Hi @cazinc thanks for raising these points!

1. This is an oversight on my part as we haven't had nested pages until now so it just didn't occur to me! Yes, they should be nested accordingly. I'll update the table.
2. Good point about the redirects. I will take another look and update the table accordingly. 
3. Thanks for your insight on the resources/support link. We do prefer that it lives in the main nav as opposed to being situated in the footer only. I think the suggestion about a button or differently styled link near or in the main nav is an interesting one. @amandafrench @lizkrznarich can you weigh in on this?

**Comment by amandafrench** [comment]
Yes, I think a button or differently styled link would be great -- needn't be in the main nav itself as long as it's available from every page and prominent.

**Comment by amandafrench** [comment]
The Documentation (aka Resources) link pointing to readme.io could actually go in the footer instead, but if that were the case I do think it should be quite large and probably also featured on the home page as a button or similar. The key requirement to my mind is that it be a persistent link from every page.

**Comment by cazinc** [comment]
Hello @amandafrench, @mariagould. Here is a very quick mockup of 2 of the options under discussion: 1) a contrasting button in the main nav and 2) a link in the footer. Option 2 is already part of the plan (issue #58). 

The option of slipping it into the homepage as a larger block could be added to issue #51 easily enough. It would give you a chance to attach some text to the link in this case and therefore some additional context/description about what users might find at the support site. 

![screenshot](https://user-images.githubusercontent.com/3863704/180403874-77cf3f42-aebc-4763-bf2f-560ff9d88994.png)

**Comment by amandafrench** [comment]
Oh, I forgot it was already in the footer! Thanks, @cazinc. I do like what you've done in Option 1 as well, so I vote for both Option 1 and Option 2 and not making it a content block on the home page, so I won't add it to #51. If we want to describe it further, we can link to it from one (or more) of the secondary pages. 

Personally I'd prefer "Documentation" as the text for both the header and the footer, and I'd prefer another color besides red for the header button, as it looks scary. :) But happy to take other suggestions from @mariagould and @lizkrznarich.

**Comment by cazinc** [comment]
Great, thanks @amandafrench. We'll do that then, and no problem with the orange for the button, that was just an artefact from having 'borrowed' the button style from the existing subscribe one. We'll use the green perhaps, as there will be a precedent for that based on issue #53). 

Text easily changed, just let me know what you decide.

**Comment by amandafrench** [comment]
Support it is then!

**Comment by mariagould** [comment]
Hi @cazinc following up on the topic of slugs and redirects, how do you propose we handle the case of ror.org/search? Since this is the primary link we share to direct people to use the registry search UI, I would prefer to avoid changing it (e.g., to ror.org/registry/search) even though in the new menu structure we want to have it nested under "Registry."

**Comment by lizkrznarich** [comment]
@mariagould @cazinc I would advise not changing the search path. Aside from that path being familiar to users and linked from other locations, we'll have to change some things in ror-app to accommodate.

**Comment by mariagould** [comment]
Yes, agreed @lizkrznarich !

**Comment by cazinc** [comment]
I think /search is handled by tor-app in any case? It doesn't exist in the ror-site repo. So it will remain where it is now. 

All other amends now done in the Summer-2022-updates branch.

**Comment by mariagould** [comment]
Hi @cazinc @bcgwebdesign - Just wanted to follow up on this item as I'm still not seeing the Support link in the main nav. I'm not sure if this is waiting on other updates with ror-site and ror-app to be finalized but wanted to mention it just in case. Thanks! 

--
> Thanks @cazinc I support going with the button in the main nav and the icon in the footer as planned per #58. Using the ROR green for the button color sounds perfect.
> 
> For the button text in the menu, we decided on "Support" at our meeting this week.

**Comment by bcgwebdesign** [comment]
Hi @mariagould 
It'll take a look at this specific tweak just now - I've a few other bits to do for you but have been otherwise detained on things this week!

**Comment by bcgwebdesign** [comment]
Hi again @mariagould - I've added that in on our branch - the hover effect on the colors is slightly off but I can tweak that.
summer-2022-updates if you can build locally?

**Comment by mariagould** [comment]
Thanks @bcgwebdesign - seeing it in my local build. Zach had suggested we make this stand out in the menu since it's a link to an external site, so we discussed making it a button style with the ROR teal, and an arrow to indicate the external link (see example - with orange as placeholder color - in July 22 comment).

**Comment by bcgwebdesign** [comment]
aha - wasn't sure if that was the proper color. Are you seeing the 'open external site' icon on your build? I had to code it in a certain way as I couldn't get my font awesome one to work!

Will change the color though and let you know

**Comment by bcgwebdesign** [comment]
try that on the local-preview @mariagould - should be proper color and i found the font awesome icon!

**Comment by mariagould** [comment]
Hi @bcgwebdesign I refreshed in my local build and I'm seeing the arrow icon now, except for on the "About" page for some reason? I'm still not seeing any color though.

**Comment by mariagould** [comment]
Thanks @bcgwebdesign merging to dev might help. It can wait until there are a few other tweaks to merge in if that works better for you.
