### ISSUE TITLE
Set up breadcrumbs or side nav for nested pages

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#50]
When users are visiting a nested page, display breadcrumbs or side nav that shows the position of the page in context. 

Example from Crossref website:

![Screen Shot 2022-07-07 at 2 19 54 PM](https://user-images.githubusercontent.com/45110557/177854839-451aa55f-dd55-4ba1-8f16-26fb7c08378e.png)

Looking at the ror-site repo, we may have already built a prorotype? https://github.com/ror-community/ror-site/blob/bdd8dd52746703efeaafbeb9e6109886567c577f/themes/hugo-ror/layouts/partials/breadcrumbs.html

**Comment by cazinc** [comment]
Breadcrumbs introduced in Summer-2022-updates. 

Let us know if you feel this is sufficient; breadcrumbs are a good way to show a user where they are in the structure, but they don't help illustrate other sibling pages in the same way that subnav would.

**Comment by mariagould** [comment]
Hi @cazinc the breadcrumbs look good. We'll be trying to minimize the number of sibling pages on the site, which means having more longer scrolling single pages. Is there anything we can do on the page to facilitate within-page navigation to different sections?

**Comment by cazinc** [comment]
Hi @mariagould there are a few options for this actually. I think if you are trying to keep sibling and child pages down, it might be sufficient to just have blocks on a page. At the moment you could even use the new callout blocks for example: just put a couple at the bottom of each page that you want to crosslink to another. This model is sort of natural if the idea is "read this page and then find more", almost like related posts links at the bottom of a blog post. If you like this model we could make it automatic too (just let me know). 

The above is not great for discovery of content that could be more relevant to a user though, as it requires they read through the page. In this case, we'd probably want to put links farther up the page if poss. It's also an option for you to just put links into copy - maybe a sort of intro block at top of each page - that lays out other useful pages. 

Let me know if either seems suitable; we can explore these further or look at other options too.

**Comment by mariagould** [comment]
Thanks @cazinc - I don't think it makes sense at this point to do the automatic "read more" boxes but we can set this up on a case-by-case basis. We'll work with the functionality we have now and see how that goes.
