### ISSUE TITLE
Create a carousel element

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#54]
ROR website editors should be able to include a carousel element on ROR webpages to highlight important news and information. 

I believe we may have previously designed one? Can we revisit this? https://github.com/ror-community/ror-site/blob/master/themes/hugo-ror/layouts/partials/carousel.html

**Comment by mariagould** [comment]
Hi @cazinc I appreciate your insights. Happy to skip the carousel in favor of a single hero image with some text overlaid. 

Regarding the recent news highlight, yes this is something we'd like to include on the homepage. I included it in the spec for #51. 

If we're skipping the carousel, we could just close this ticket for now and focus on the work outlined in #51.

**Comment by cazinc** [comment]
Great, will do, thanks @mariagould
