### ISSUE TITLE
Optimize font and heading sizes

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#56]
The current font sizing on the ROR website can make text-heavy pages unwieldy to navigate. When we switch the website fonts (see #45) we should make sure the heading styles and body text are sized to optimize readability.

**Comment by cazinc** [comment]
Done in the Summer-2022-updates branch of roe-site. Will add a separate card for ror-app. 

We have made the following changes designed to enhance readability:

1. Headings a bit bigger, and now bold to set them apart from text more
2. The banner area is a bit taller now as a result of the increase in size to the H1
3. Spacing under subheads reduced, to connect them better to the related text
4. Line spacing increased a bit
5. Paragraph and List elements now have increased spacing between, to help separate them better
6. Links are now, to make them more obvious

Although the main goal was accessibility & readability, to some extent these sorts of amends are also a design change, and so somewhat subjective. Please us know if you want anything bigger/smaller/etc.

**Comment by mariagould** [comment]
Thanks @cazinc these changes look great. 

The only thing I noticed is that we seem to be running into line spacing issues with longer H1s and page titles, e.g., /community and /blog/2022-06-13-welcome-amanda-french/. Attaching screenshots of what I see on my end. Can this be addressed, or should we aim to keep these titles and headers as short as possible to avoid running into the issue?

![Screen Shot 2022-08-08 at 2 14 25 PM](https://user-images.githubusercontent.com/45110557/183516461-d01e9e08-2376-4a1d-b8cd-ce3d17165ef4.png)
![Screen Shot 2022-08-08 at 2 14 36 PM](https://user-images.githubusercontent.com/45110557/183516471-b95c138f-588f-4e8b-b5cb-215532a6651b.png)

**Comment by cazinc** [comment]
Hi @mariagould - def can be addressed, just something that's come about after later changes. Will fix.
