### ISSUE TITLE
Create a callout box element

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#57]
ROR website editors need to be able to incorporate a callout box element that can draw attention to important announcements or sidebar information. 

The box should look something like the example from Readme.io below, with the ability to choose from a few different shading and icon options.
------

![Screen Shot 2022-07-07 at 2 25 06 PM](https://user-images.githubusercontent.com/45110557/177856226-95c2907c-f812-4a70-8cd0-67163f70daa8.png)

**Comment by cazinc** [comment]
We have created a shortcode for this in the Summer-2022-updates branch, which allows for some variation in colour and icon. Have a look at http://localhost:1313/test/ locally to see, and look at ../content/test/_index.md to read about how to use the new shortcode. Screenshot attached here for ref too.

![screencapture-localhost-1313-test-2022-08-07-18_36_00](https://user-images.githubusercontent.com/3863704/183303867-0fed539e-94fc-4ae3-9923-c343f16010e0.png)

**Comment by mariagould** [comment]
The callouts look great!

**Comment by mariagould** [comment]
Documenting feedback from review discussion: change the beige box color to a light gray.

**Comment by cazinc** [comment]
Now fixed in Summer-2022-updates, will merge to dev.
