### ISSUE TITLE
re-redirect www

### ISSUE THREAD

**Issue by ynnig** [ror-community/ror-site#6]
Hey @mfenner or @gbilder - a twitter user reported that www.ror.org no longer redirects to https://ror.org. Can you look into it? https://twitter.com/JGudler/status/1092709436886532097

**Comment by mfenner** [comment]
The issue is http -> https redirection on top of redirecting www.ror.org to ror.org doesn't work. Will look into this.

**Comment by mariagould** [comment]
https://www.ror.org resolves successfully but http://www.ror.org does not. Screenshot attached. 
![Screen Shot 2020-04-03 at 7 38 02 AM](https://user-images.githubusercontent.com/45110557/78376092-ab65df80-7582-11ea-8dfc-3507a92243db.png)

**Comment by cazinc** [comment]
Hi @mariagould not to stick our noses in, but I see this is still an issue. Not something we can resolve I'm afraid, needs to be someone who has oversight over hosting of the site.

**Comment by lizkrznarich** [comment]
@mariagould @cazinc This is on our radar in the [ROR Inbox](https://github.com/orgs/ror-community/projects/11#card-77218645), it just hasn't been a particularly high priority. I will take care of it in the next couple of weeks, along with a few other small things.

**Comment by cazinc** [comment]
Great, thanks @lizkrznarich

**Comment by mariagould** [comment]
Thanks for taking a look @cazinc. I know there are a few legacy issues in the ror-site repo and this is one of them. As Liz mentioned, it's still on our radar (and being tracked on a different project board) but hasn't been a top priority.

**Comment by lizkrznarich** [comment]
@cazinc www is now correctly redirecting to ror.org UI in all envs. additionally, http://www should now correctly redirect to https://www .
