### ISSUE TITLE
"Ruminations on Russia" in Disqus

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#7]
Disqus displays "Ruminations on Russia" - can we remove/change? 
![screen shot 2019-02-15 at 9 47 21 am](https://user-images.githubusercontent.com/45110557/52877019-b014cd80-310d-11e9-857c-399b96fbe00a.png)

**Comment by mariagould** [comment]
@ynnig do you have any idea how to fix this?

**Comment by ynnig** [comment]
fixed disqus shortname "ror" to "ror-community"

**Comment by amandafrench** [comment]
Removed Disqus altogether in #78
