### ISSUE TITLE
Upgrade Font Awesome to 5.x 

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-site#86]
We need the Mastodon icon (among others) for our new social footer and so need to upgrade Font Awesome from 4.7 to at least 5.0 sitewide. This will affect ror-app as well.

**Comment by lizkrznarich** [comment]
ror-site: https://github.com/ror-community/ror-site/pull/93
ror-app: https://github.com/ror-community/ror-app/releases/tag/1.2.0
