### ISSUE TITLE
Set up social preview for blog posts

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#97]
**Describe the problem you would like to solve**
When we share ROR blog posts on social media sites (Twitter, LinkedIn), a preview of the content would make the posting more eye-catching and accessible. Currently, our blog links do not do this, so we need to add more detail to social posts and manually upload any visuals. Screenshots show sample tweet linking to a ROR blog post vs. DataCite blog. 

**Describe the solution you'd like**
Set up blog posts to generate an auto-preview when they are shared on social media. 

**Who would benefit from this feature?**
ROR comms team, social media followers.

**Additional information**
<img width="594" alt="Screen Shot 2023-01-24 at 5 53 33 PM" src="https://user-images.githubusercontent.com/45110557/214463067-0220b630-2e5c-4822-905c-1418f88fd1aa.png">
<img width="603" alt="Screen Shot 2023-01-24 at 5 53 03 PM" src="https://user-images.githubusercontent.com/45110557/214463069-4952167e-9f6d-4cf2-99d0-4ef415052606.png">

**Comment by amandafrench** [comment]
@mariagould I've deployed the Twitter Card feature to dev.ror.org -- try it out with the Caltech blog post (obviously without actually posting the tweet!). Note that making the feature work does involve adding some additional content to the front matter of the blog post, so right now it will only work with that blog post. I've put an empty copy of the necessary front matter at /content/test/_post.md and have also set up a blog post archetype (though I don't think our site is configured for Hugo archetypes yet). 
<img width="643" alt="Screenshot 2023-02-22 at 8 00 02 AM" src="https://user-images.githubusercontent.com/227453/220627153-447d4d83-4270-4931-b454-ed7dd4790ea4.png">

**Comment by amandafrench** [comment]
Resolved in [this commit](https://github.com/ror-community/ror-site/commit/079e5dddd91d0bbd1e059af4d00a164fd731538b)
